fixed syntax

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -1,31 +1,38 @@
 name: Deploy Next Application
 
-on: 
-  push: 
-    branches: 
-      -master
+on:
+  push:
+    branches:
+      - master  # Ensure the branch name is correct
+
 jobs:
-  build: 
+  build:
     runs-on: ubuntu-latest
-    steps: 
+    steps:
       - name: Checkout Source
         uses: actions/checkout@v4
+
       - name: Create .env file
         run: echo "MESSAGE=${{secrets.MESSAGE}}" >> .env
+
       - name: Build Docker Image
         run: docker build -t rajaputrarohit/deploy-test-demo .
+
       - name: Login to DockerHUB
-        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}} 
+        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+
       - name: Publish image to DockerHub
         run: docker push rajaputrarohit/deploy-test-demo:latest
 
-  deploy: 
+  deploy:
     needs: build
     runs-on: self-hosted
-    steps: 
-      - name: Pull image from Docker Hub 
-        run: docker pull  rajaputrarohit/deploy-test-demo:latest
+    steps:
+      - name: Pull image from Docker Hub
+        run: docker pull rajaputrarohit/deploy-test-demo:latest
+
       - name: Delete old container
-        run: docker rm -f next-js-app-container
+        run: docker rm -f next-js-app-container || true  # Prevent failure if container doesn't exist
+
       - name: Run Docker Container
         run: docker run -d -p 3000:3000 --name next-js-app-container rajaputrarohit/deploy-test-demo
